//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogistiQ.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliveries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deliveries()
        {
            this.DeliveryDetails = new HashSet<DeliveryDetails>();
        }
    
        public int DeliveryID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public decimal Cost { get; set; }
        public string Status { get; set; }
        public Nullable<int> WarehouseID { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
        public virtual Warehouses Warehouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryDetails> DeliveryDetails { get; set; }
    }
}
