//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogistiQ.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryDetails
    {
        public int DeliveryDetailID { get; set; }
        public Nullable<int> DeliveryID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
    
        public virtual Deliveries Deliveries { get; set; }
        public virtual Products Products { get; set; }
    }
}
